# Generated by Django 4.2.9 on 2024-02-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_num_copies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="num_copies",
        ),
    ]
